### ISSUE TITLE
Provide support for InputStream as input

### ISSUE THREAD

**Issue by Ranjanshivam9** [tlabs-data/tablesaw-parquet#54]
First of thanks for this extension I am able to read files but I am required to read from inputStream coming from Amazon S3.

I didnt find any builder method which accepts inputStreams is it possible to read input stream ?
![Screenshot (2)](https://user-images.githubusercontent.com/15106647/161500815-052ac7bc-a592-4fd5-89f4-aef3d5c25617.png)

**Comment by Ranjanshivam9** [comment]
Hi @ccleva Thanks for the response ! Can we use InputFile instead files as source as I can see a Builder method which accepts InputFile . But I am just way too junior to under stand how to implement it .
https://stackoverflow.com/questions/58141248/read-parquet-data-from-bytearrayoutputstream-instead-of-file

found this thing where we can convert stream into InputFile . Do you think such approach can work here ?

**Comment by ccleva** [comment]
Hi @Ranjanshivam9. A custom InputFile would work, similar to the example you provided (thanks for the link !). The implementation shown there loads the whole InputStream in memory, so it will require additional work to make it scale for very large file.

The focus of the next version will be to provide proper support for remote files. I will include support for user provided InputStream too, now that there is a need for it. I just need to find a solution suitable regardless of stream size.

Keep watching this issue, but don't worry if it takes me longer than you would like ...

**Comment by ccleva** [comment]
Hi @Ranjanshivam9. Support for remote files, including on AWS, was added in version 0.10.0 - available for tablesaw 0.42.0 and up. See the updated README for details. This new version also supports using a tablesaw Source created from an InputStream.

I hope this fits your needs. Feel free to reopen this issue or create a new one if you still have troubles with the library.
