### ISSUE TITLE
Ability to save without .crc files

### ISSUE THREAD

**Issue by hoggatt** [tlabs-data/tablesaw-parquet#80]
First off, I love this library, thank you for making it so easy to read and write parquet files in Java!

One minor annoyance is that saving parquet files generates hidden .crc files. It appears that there is a way to turn this off in the underlying library (example [here](https://stackoverflow.com/questions/26333886/how-to-avoid-creation-of-crc-files-when-parquet-files-are-created)). Would it be possible to expose that option (`withValidation`) to the `TablesawParquetWriteOptions` builder?

**Comment by ccleva** [comment]
Hi @hoggatt. Thank you for your feedback, and for your kind words.

Sorry for the inconvenience, I never looked at that aspect of the hadoop-based writer. I have now, thanks to you, but it's a bit different than what is described in the link you provided (we are actually using a different writer class).

I have found the right solution now, and I'm thinking of not generating these crc files by default and provide the option to generate them if needed. I'll include this in the next release. In the meantime, you can disable this hadoop feature on your side by adding this bit of code prior to writing parquet files (in a try/catch block):

```
org.apache.hadoop.fs.FileSystem fs = org.apache.hadoop.fs.FileSystem.getLocal(new org.apache.hadoop.conf.Configuration());
fs.setWriteChecksum(false);
```
Thanks again for giving me the opportunity to dive into this topic.

**Comment by hoggatt** [comment]
Thank you! This is extremely helpful! I appreciate you digging into it.

**Comment by ccleva** [comment]
Hi @hoggatt. This has been fixed in [v0.12.0](https://github.com/tlabs-data/tablesaw-parquet/releases/tag/0.43.3-v0.12.0).

**Comment by hoggatt** [comment]
Hi @ccleva, the latest version (0.12.0) does not appear in maven central. Is there some other way you recommend adding the updated version to my POM?

**Comment by ccleva** [comment]
Hi @hoggatt, the latest version was updated for the tablesaw 0.43.3 maintenance release but is compatible with all 0.43.x versions. The [artifact](https://central.sonatype.com/artifact/net.tlabs-data/tablesaw_0.43.3-parquet/0.12.0) is in maven central as

```
<dependency>
    <groupId>net.tlabs-data</groupId>
    <artifactId>tablesaw_0.43.3-parquet</artifactId>
    <version>0.12.0</version>
</dependency>
```

Sorry if that was not clear from the [release notes](https://github.com/tlabs-data/tablesaw-parquet/releases/tag/0.43.3-v0.12.0)
